# File structure version
version: '3'

services:
  # Database based on official postgres image
  db:
    image: postgres
    hostname: db
    volumes:
      - "./db:/var/lib/postgresql/data"

  # Our django application
  # Build from remote dockerfile
  # Connect local app folder with image fodler, so changes will be push to image instantly
  # Open port 8000

  apr:
    build:
      context: .
      dockerfile: config/apr/Dockerfile
    hostname: apr
    volumes:
      - ./apr:/apr
    expose:
      - "8000"
    depends_on:
      - db


  # Web server based on official nginx image
  # Connect external 8000 which you can access from brower)
  # with internal port 8000 (which will be linked to app port 8000 in configs)
  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - apr







